### ISSUE TITLE
v13 todo - notes

### ISSUE THREAD

**Issue by Plushtoast** [Plushtoast/dsa5-foundryVTT#1799]
- [x] waypoint movement https://discord.com/channels/170995199584108546/1296292044011995136/1296783192166109216
- [x] https://github.com/foundryvtt/foundryvtt/issues/8755
- [x] https://github.com/foundryvtt/foundryvtt/issues/11648
- [x] https://github.com/foundryvtt/foundryvtt/issues/11678
- [x] https://github.com/foundryvtt/foundryvtt/issues/9637
- [x] https://github.com/foundryvtt/foundryvtt/issues/11668
- [x] https://github.com/foundryvtt/foundryvtt/issues/11419
- [x] https://github.com/foundryvtt/foundryvtt/issues/11754
- [x] https://github.com/foundryvtt/foundryvtt/issues/11426
- [x] https://github.com/foundryvtt/foundryvtt/issues/12024
- [x] https://github.com/foundryvtt/foundryvtt/issues/12062
